version: '3.8'

services:
  gas:
    image: dannyshih/gas:v11.4.1
    container_name: gas_dev_app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      GAS_DB_HOST: db
    volumes:
      - ./config/config.json:/home/node/app/config.json

  db:
    image: mongo:7.0.3
    container_name: gas_dev_db
    restart: unless-stopped
    ports:
      - "8001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dumbledore
    volumes:
      - gas_dev_db:/data/db
      - gas_dev_dbconfigsvr:/data/configdb

volumes:
  gas_dev_db:
  gas_dev_dbconfigsvr:
