services:
  gas:
    image: registry.internal.dannyshih.net:5000/gas:v12.3.0
    container_name: gas_dev_app
    restart: unless-stopped
    ports:
      - "8000:80"
    environment:
      GAS_DB_HOST: db
    volumes:
      - ./config/config.json:/home/node/app/config.json

  gasSandbox:
    image: node:22.12.0
    container_name: gas_dev_sandbox
    restart: unless-stopped
    ports:
      - "8001:80"
    environment:
      GAS_DB_HOST: db
    volumes:
      - ./config/config.json:/home/node/app/config.json
      - ../:/home/node/app
    working_dir: /home/node/app
    entrypoint: [ "node", "app.js" ]

  db:
    image: mongo:8.0.1
    container_name: gas_dev_db
    restart: unless-stopped
    ports:
      - "8002:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dumbledore
    volumes:
      - gas_dev_db:/data/db
      - gas_dev_dbconfigsvr:/data/configdb

  mongo-express:
    image: mongo-express:1.0.2
    container_name: gas_mongo-express
    restart: unless-stopped
    ports:
      - "9001:80"
    environment:
      # None of the documented _FILE variables in this project appear to be respected.
      # So to keep the mongo password out of this file, we need to use .env
      ME_CONFIG_MONGODB_URL: mongodb://root:dumbledore@db:27017/?ssl=false
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH: "false"
      PORT: 80

volumes:
  gas_dev_db:
  gas_dev_dbconfigsvr:
